<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-02-26 at 16:45:27.
 */

use PHPUnit\Framework\TestCase;
include '/includes/class.utils.inc.php';

//C:\wamp\www\GSB_AppliMVC\www\includes\

class UtilsTest extends TestCase {

    /**
     * @var Utils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Utils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (array("toto", "zozo"), "toto") == true.
     *
     * @covers Utils::estVisiteur
     */
    public function testEstVisiteur() {
        $this->assertTrue(
                Utils::estVisiteur(array("toto", "zozo"), "toto")
        );
    }

    /**
     * Generated from @assert (array("toto", "zozo"), "coco") == false.
     *
     * @covers Utils::estVisiteur
     */
    public function testEstVisiteur2() {
        $this->assertFalse(
                Utils::estVisiteur(array("toto", "zozo"), "coco")
        );
    }

    /**
     * Generated from @assert (array("toto", "zozo"), 0) == false.
     *
     * @covers Utils::estVisiteur
     */
    public function testEstVisiteur3() {
        $this->assertFalse(
                Utils::estVisiteur(array("toto", "zozo"), 0)
        );
    }

    /**
     * Generated from @assert ("coco", "toto") == false.
     *
     * @covers Utils::estVisiteur
     */
    public function testEstVisiteur4() {
        $this->assertFalse(
                Utils::estVisiteur("coco", "toto")
        );
    }

    /**
     * Generated from @assert (1, 1) == false.
     *
     * @covers Utils::estVisiteur
     */
    public function testEstVisiteur5() {
        $this->assertFalse(
                Utils::estVisiteur(1, 1)
        );
    }

    /**
     * Generated from @assert ('2018-02-26') == '26/02/26'.
     *
     * @covers Utils::dateAnglaisVersFrancais
     */
    public function testDateAnglaisVersFrancais() {
        $this->assertEquals(
                '26/02/26',
                Utils::dateAnglaisVersFrancais('2018-02-26')
        );
    }

    /**
     * Generated from @assert ('1999-11-09') == '09/11/1999'.
     *
     * @covers Utils::dateAnglaisVersFrancais
     */
    public function testDateAnglaisVersFrancais2() {
        $this->assertEquals(
                '09/11/1999',
                Utils::dateAnglaisVersFrancais('1999-11-09')
        );
    }

    /**
     * Generated from @assert ('1999') == '//1999'.
     *
     * @covers Utils::dateAnglaisVersFrancais
     */
    public function testDateAnglaisVersFrancais3() {
        $this->assertEquals(
                '//1999',
                Utils::dateAnglaisVersFrancais('1999')
        );
    }

    /**
     * Generated from @assert (02) == '//2'.
     *
     * @covers Utils::dateAnglaisVersFrancais
     */
    public function testDateAnglaisVersFrancais4() {
        $this->assertEquals(
                '//2',
                Utils::dateAnglaisVersFrancais(02)
        );
    }

    /**
     * @covers Utils::estConnecte
     * @todo   Implement testEstConnecte().
     */
    public function testEstConnecte() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::estComptable
     * @todo   Implement testEstComptable().
     */
    public function testEstComptable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::connecter
     * @todo   Implement testConnecter().
     */
    public function testConnecter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::deconnecter
     * @todo   Implement testDeconnecter().
     */
    public function testDeconnecter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::dateFrancaisVersAnglais
     * @todo   Implement testDateFrancaisVersAnglais().
     */
    public function testDateFrancaisVersAnglais() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::getMois
     * @todo   Implement testGetMois().
     */
    public function testGetMois() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::getMoisPrecedent
     * @todo   Implement testGetMoisPrecedent().
     */
    public function testGetMoisPrecedent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::getMoisSuivant
     * @todo   Implement testGetMoisSuivant().
     */
    public function testGetMoisSuivant() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::estEntierPositif
     * @todo   Implement testEstEntierPositif().
     */
    public function testEstEntierPositif() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::estTableauEntiers
     * @todo   Implement testEstTableauEntiers().
     */
    public function testEstTableauEntiers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::estJourComprisDansIntervalle
     * @todo   Implement testEstJourComprisDansIntervalle().
     */
    public function testEstJourComprisDansIntervalle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::estDateDepassee
     * @todo   Implement testEstDateDepassee().
     */
    public function testEstDateDepassee() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::estDateValide
     * @todo   Implement testEstDateValide().
     */
    public function testEstDateValide() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::lesQteFraisValides
     * @todo   Implement testLesQteFraisValides().
     */
    public function testLesQteFraisValides() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::valideInfosFrais
     * @todo   Implement testValideInfosFrais().
     */
    public function testValideInfosFrais() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::ajouterErreur
     * @todo   Implement testAjouterErreur().
     */
    public function testAjouterErreur() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::ajouterSucces
     * @todo   Implement testAjouterSucces().
     */
    public function testAjouterSucces() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::nbErreurs
     * @todo   Implement testNbErreurs().
     */
    public function testNbErreurs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utils::mentionRefuse
     * @todo   Implement testMentionRefuse().
     */
    public function testMentionRefuse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
